[package]
name = "imnodes-wgpu-examples"
version = "0.1.0"
authors = ["Benedikt Mandelkow <benedikt.mandelkow@rwth-aachen.de>", "imgui-wgpu contributors"]
edition = "2018"

[dependencies]
imnodes = { path = "../" }

wgpu = "0.8"
winit = "0.24" # opening windows and handling input
futures = "0.3" # executing async functions using blocking executor
imgui = "0.7"
imgui-winit-support = "0.7" # connection of input (keys) to imgui
imgui-wgpu = "0.15" # imgui backend for drawing using wgpu
